### ISSUE TITLE
Allow for local fs config to turn packages off and on

### ISSUE THREAD

**Issue by adamclerk** [aminya/package-switch#2]
I have a few projects that use JSHint and others that use ESLint. I'd very much like a config in the root folder that package-switch evaluates when atom is opened. 

project 1

``` json
{
  "disabled": ["eslint"]
}
```

project 2

``` json
{
  "disabled": ["jshint"]
}
```

**Comment by fstiewitz** [comment]
Interesting idea. It's on my list.

**Comment by adamclerk** [comment]
ty

**Comment by fstiewitz** [comment]
Added in `v0.4.0`.
Create a file called `.package-switch.cson` in the project's root folder and set whatever linter you use to enabled and the other to disabled.
Only limitation is that it only auto-executes the file config if there is only one active project, so multi-project work environments are not supported.

**Comment by adamclerk** [comment]
You rock Fabian. Thanks so much.
